feat: testnet dencun update
lukso-network/network-docker-containers pull request #16
Opened 2024-03-26 15:10 UTC by Wolmin

This PR provides the suggested versions for running a dencun node using docker-compose

2024-03-27 08:13 UTC, richtera approved these changes

2024-03-29 11:18 UTC, mxmar requested changes
@Wolmin Let's add `Nethermind` to this PR

2024-05-06 14:22 UTC, mxmar approved these changes

2024-05-06 15:15 UTC, frozeman approved these changes

2024-05-06 15:15 UTC, frozeman approved these changes

2024-05-06 15:15 UTC, merged